[package]
name = "recolor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.24.5"
thiserror = "1.0"
color_space = "0.5.3"
wasm-bindgen = "0.2"
js-sys = "0.3.45"
